#ifndef ARDUINO_MAIN_PLAIN_CCODE_H
#define ARDUINO_MAIN_PLAIN_CCODE_H

static const char *arduino_pong_code =
    "import math\n"
    "import json\n"
    "\n"
    "LCD_WIDTH = 128\n"
    "LCD_HEIGHT = 64\n"
    "\n"
    "PADDLE_WIDTH = 4\n"
    "PADDLE_HEIGHT = 14\n"
    "PADDLE_BORDER = PADDLE_WIDTH // 2 + 3\n"
    "PADDLE_SPEED = 80\n"
    "PADDLE_AUTO_SPEED = 55\n"
    "\n"
    "PUCK_START_SPEED = 40\n"
    "PUCK_PLAY_SPEED = 120\n"
    "PUCK_RADIUS = 2\n"
    "\n"
    "MAX_DT = 0.05\n"
    "\n"
    "COLLISION_TOLERANCE = 3\n"
    "\n"
    "def _sign(val):\n"
    "    if val > 0:\n"
    "        return 1\n"
    "    if val < 0:\n"
    "        return -1\n"
    "    return 0\n"
    "\n"
    "_PUCK_VELOCITIES = [\n"
    "    ( 0.299777,  0.278854),\n"
    "    (-0.723800, -0.510216),\n"
    "    (-1.299285,  0.353399),\n"
    "    (-0.198242,  0.180985),\n"
    "    (-1.415851, -0.562724),\n"
    "    ( 0.385606,  0.122490),\n"
    "    (-1.547527, -0.559119),\n"
    "    ( 0.765541,  0.517615),\n"
    "    ( 0.468526, -0.319499),\n"
    "    ( 1.702367, -0.795579),\n"
    "    (-1.953737,  0.694989),\n"
    "    ( 1.198595,  0.459464),\n"
    "    ( 1.583319, -0.842400),\n"
    "    (-0.481705,  0.154704),\n"
    "    (-1.070532,  0.322527),\n"
    "    ( 2.557897,  0.710635),\n"
    "    ( 1.290885, -0.444053),\n"
    "    ( 1.393786, -0.674692),\n"
    "    (-1.231363,  0.403641),\n"
    "    (-0.330321,  0.218262),\n"
    "    (-1.439538, -0.673195),\n"
    "    (-1.302843,  0.369229),\n"
    "    ( 0.594090, -0.541904),\n"
    "    ( 0.236921, -0.197670),\n"
    "    ( 1.435542, -0.574747),\n"
    "    ( 1.013453, -0.714257),\n"
    "    ( 1.129002,  0.494028),\n"
    "    (-1.101814, -0.276007),\n"
    "    (-0.024249,  0.019053),\n"
    "    (-1.053354,  0.722206),\n"
    "    (-1.323984,  0.584159),\n"
    "    ( 0.642460, -0.230465),\n"
    "    (-0.227863,  0.058229),\n"
    "    ( 0.484477,  0.360567),\n"
    "    ( 1.085422,  0.537197),\n"
    "    ( 0.308061, -0.130469),\n"
    "    (-3.101142,  0.943776),\n"
    "    (-1.404513,  0.741037),\n"
    "    (-2.282604, -0.694321),\n"
    "    (-0.487959,  0.197889),\n"
    "    ( 3.120547,  0.858197),\n"
    "    (-0.897647, -0.521095),\n"
    "    (-2.036904, -0.828693),\n"
    "    (-2.483721,  0.955969),\n"
    "    (-1.802931, -0.743217),\n"
    "    ( 1.699721, -0.469887),\n"
    "    (-3.516844,  0.928726),\n"
    "    ( 0.935688,  0.425898),\n"
    "    (-0.316027, -0.123800),\n"
    "    (-0.601032, -0.504189),\n"
    "]\n"
    "\n"
    "class Vector:\n"
    "\n"
    "    def __init__(self, x=0.0, y=0.0):\n"
    "        self.x = float(x)\n"
    "        self.y = float(y)\n"
    "        self.magnitude = 0.0\n"
    "        self.angle = 0.0\n"
    "        self._recalc()\n"
    "\n"
    "    def _recalc(self):\n"
    "        self.magnitude = math.sqrt(self.x * self.x + self.y * self.y)\n"
    "        if self.magnitude:\n"
    "            self.angle = math.atan2(self.y, self.x)\n"
    "        else:\n"
    "            self.angle = 0.0\n"
    "\n"
    "    def set(self, x, y):\n"
    "        self.x, self.y = float(x), float(y)\n"
    "        self._recalc()\n"
    "        return self\n"
    "\n"
    "    def set_magnitude(self, mag):\n"
    "        if self.magnitude:\n"
    "            scale = float(mag) / self.magnitude\n"
    "            self.x = self.x * scale\n"
    "            self.y = self.y * scale\n"
    "        self.magnitude = float(mag)\n"
    "        return self\n"
    "\n"
    "    def set_angle(self, angle):\n"
    "        self.x = self.magnitude * math.cos(angle)\n"
    "        self.y = self.magnitude * math.sin(angle)\n"
    "        self.angle = float(angle)\n"
    "        return self\n"
    "\n"
    "    def flip_y(self):\n"
    "        self.y = 0.0 - self.y\n"
    "        self._recalc()\n"
    "        return self\n"
    "\n"
    "    def flip_x(self):\n"
    "        self.x = 0.0 - self.x\n"
    "        self._recalc()\n"
    "        return self\n"
    "\n"
    "class Paddle:\n"
    "\n"
    "    def __init__(self, x):\n"
    "        self.position = Vector(x, LCD_HEIGHT / 2)\n"
    "        self.speed = PADDLE_SPEED\n"
    "        self.score = 0\n"
    "        self.is_auto = False\n"
    "        self._up = False\n"
    "        self._down = False\n"
    "\n"
    "    def set_input(self, direction):\n"
    "        if direction == \"up\":\n"
    "            self._up = True\n"
    "            self._down = False\n"
    "        elif direction == \"down\":\n"
    "            self._up = False\n"
    "            self._down = True\n"
    "        else:\n"
    "            self._up = False\n"
    "            self._down = False\n"
    "\n"
    "    def update(self, dt, puck):\n"
    "        if self.is_auto:\n"
    "            self.speed = PADDLE_AUTO_SPEED\n"
    "            if _sign(self.position.x - puck.position.x) == _sign(puck.velocity.x):\n"
    "                diff = puck.position.y - self.position.y\n"
    "                if diff < -self.speed * dt:\n"
    "                    self.position.y = self.position.y - self.speed * dt\n"
    "                elif diff > self.speed * dt:\n"
    "                    self.position.y = self.position.y + self.speed * dt\n"
    "        else:\n"
    "            direction = 0\n"
    "            if self._up:\n"
    "                direction = -1\n"
    "            elif self._down:\n"
    "                direction = 1\n"
    "            self.position.y = self.position.y + self.speed * dt * direction\n"
    "\n"
    "        half_h = PADDLE_HEIGHT / 2\n"
    "        _py = self.position.y\n"
    "        if _py < half_h:\n"
    "            _py = half_h\n"
    "        if _py > LCD_HEIGHT - half_h:\n"
    "            _py = LCD_HEIGHT - half_h\n"
    "        self.position.y = _py\n"
    "\n"
    "class Puck:\n"
    "\n"
    "    def __init__(self, left, right):\n"
    "        self.position = Vector()\n"
    "        self.velocity = Vector()\n"
    "        self.left = left\n"
    "        self.right = right\n"
    "        self._vel_idx = 0\n"
    "        self.reset(0)\n"
    "\n"
    "    def _next_velocity(self):\n"
    "        vx, vy = _PUCK_VELOCITIES[self._vel_idx]\n"
    "        self._vel_idx = self._vel_idx + 1\n"
    "        if self._vel_idx >= 50:\n"
    "            self._vel_idx = 0\n"
    "        return vx, vy\n"
    "\n"
    "    def reset(self, state):\n"
    "        if state > 0:\n"
    "            self.right.score = self.right.score + 1\n"
    "        elif state < 0:\n"
    "            self.left.score = self.left.score + 1\n"
    "\n"
    "        self.position.set(LCD_WIDTH / 2, LCD_HEIGHT / 2)\n"
    "        _vx, _vy = self._next_velocity()\n"
    "        self.velocity.set(_vx, _vy)\n"
    "        self.velocity.set_magnitude(PUCK_START_SPEED)\n"
    "\n"
    "    def update(self, dt):\n"
    "        self.position.x = self.position.x + self.velocity.x * dt\n"
    "        self.position.y = self.position.y + self.velocity.y * dt\n"
    "        self.position._recalc()\n"
    "        self._collide()\n"
    "        self._bounce()\n"
    "        self._score()\n"
    "\n"
    "    def _score(self):\n"
    "        if self.position.x > LCD_WIDTH + PUCK_RADIUS:\n"
    "            self.reset(-1)\n"
    "        elif self.position.x < -PUCK_RADIUS:\n"
    "            self.reset(1)\n"
    "\n"
    "    def _bounce(self):\n"
    "        if self.position.y < PUCK_RADIUS:\n"
    "            self.velocity.flip_y()\n"
    "        elif self.position.y > LCD_HEIGHT - PUCK_RADIUS:\n"
    "            self.velocity.flip_y()\n"
    "\n"
    "    def _collide(self):\n"
    "        half_w = PADDLE_WIDTH / 2\n"
    "        half_h = PADDLE_HEIGHT / 2\n"
    "\n"
    "        on_left = self.position.x - PUCK_RADIUS < self.left.position.x + half_w\n"
    "        on_right = self.position.x + PUCK_RADIUS > self.right.position.x - half_w\n"
    "\n"
    "        if on_left and self._between_paddle(self.left.position):\n"
    "            angle = ((self.position.y - (self.left.position.y - half_h)) / PADDLE_HEIGHT * math.pi / 2 - math.pi / 4)\n"
    "            self.velocity.set_angle(angle)\n"
    "            self.velocity.set_magnitude(PUCK_PLAY_SPEED)\n"
    "\n"
    "        if on_right and self._between_paddle(self.right.position):\n"
    "            angle = ((self.position.y - (self.right.position.y - half_h)) / PADDLE_HEIGHT * math.pi / 2 - math.pi / 4)\n"
    "            self.velocity.set_angle(angle)\n"
    "            self.velocity.flip_x()\n"
    "            self.velocity.set_magnitude(PUCK_PLAY_SPEED)\n"
    "\n"
    "    def _between_paddle(self, paddle_pos):\n"
    "        half_h = PADDLE_HEIGHT / 2\n"
    "        y_top = paddle_pos.y - half_h\n"
    "        y_bot = paddle_pos.y + half_h\n"
    "        if self.position.y + PUCK_RADIUS + COLLISION_TOLERANCE <= y_top:\n"
    "            return False\n"
    "        if self.position.y - PUCK_RADIUS - COLLISION_TOLERANCE >= y_bot:\n"
    "            return False\n"
    "        return True\n"
    "\n"
    "_STATE_SPLASH = 0\n"
    "_STATE_PLAY = 1\n"
    "_STATE_QUIT = 2\n"
    "\n"
    "class Game:\n"
    "\n"
    "    def __init__(self):\n"
    "        self.left  = Paddle(PADDLE_BORDER)\n"
    "        self.right = Paddle(LCD_WIDTH - PADDLE_BORDER)\n"
    "        self.puck  = Puck(self.left, self.right)\n"
    "        self._state = _STATE_SPLASH\n"
    "\n"
    "    def step(self, data, dt):\n"
    "        if isinstance(data, str):\n"
    "            data = json.loads(data)\n"
    "        if self._state == _STATE_SPLASH:\n"
    "            return self._step_splash(data)\n"
    "        if self._state == _STATE_PLAY:\n"
    "            return self._step_play(data, dt)\n"
    "        return \"\"\n"
    "\n"
    "    def _step_splash(self, data):\n"
    "        if data.get(\"quit\"):\n"
    "            self._do_quit()\n"
    "            return \"\"\n"
    "\n"
    "        start = data.get(\"start\", \"\")\n"
    "        if start == \"single\":\n"
    "            self.left.is_auto = True\n"
    "            self._begin_play()\n"
    "        elif start == \"multi\":\n"
    "            self._begin_play()\n"
    "        return \"\"\n"
    "\n"
    "    def _step_play(self, data, dt):\n"
    "        if data.get(\"quit\"):\n"
    "            self._do_quit()\n"
    "            return \"\"\n"
    "\n"
    "        self.left.set_input(data.get(\"player1\", \"none\"))\n"
    "\n"
    "        self.right.set_input(data.get(\"player2\", \"none\"))\n"
    "\n"
    "        self.left.update(dt, self.puck)\n"
    "        self.right.update(dt, self.puck)\n"
    "        self.puck.update(dt)\n"
    "\n"
    "        _px = str(int(self.puck.position.x))\n"
    "        _py = str(int(self.puck.position.y))\n"
    "        _ly = str(int(self.left.position.y))\n"
    "        _ry = str(int(self.right.position.y))\n"
    "        _ls = str(self.left.score)\n"
    "        _rs = str(self.right.score)\n"
    "        return _px + \",\" + _py + \",\" + _ly + \",\" + _ry + \",\" + _ls + \",\" + _rs\n"
    "\n"
    "    def _begin_play(self):\n"
    "        self._state = _STATE_PLAY\n"
    "\n"
    "    def _do_quit(self):\n"
    "        self._state = _STATE_QUIT\n"
    "\n"
    "_game = Game()\n"
    "\n"
    "def render_frame(data, dt):\n"
    "    return _game.step(data, dt)\n"
    "\n"
    "def render_frame_no_dt(data):\n"
    "    return _game.step(data, 0.05)\n"
    "\n"
    "r = render_frame('{ \"start\": \"multi\" }', 0.05)\n"
    "r = render_frame('{ \"player1\": \"down\" }', 0.05)\n"
    "print(r)\n"
    "r = render_frame('{ \"player1\": \"down\" }', 0.05)\n"
    "print(r)\n";

#endif
